menu=\n \
Выберите пункт меню:\n \
 \n \
1. Добавить аренду пользователю \n \
2. Взаимодействовать с Bikes\n \
3. Взаимодействовать с Cars\n \
4. Взаимодействовать с Users\n \
5. Выход в предыдущее меню

enter=\n \
Добро пожаловать в RentalServiceApp\n \
Тут осуществляется взаимодействие с арендой наших товаров\n \
Введите пароль администратора, или exit для выхода

crud=\n \
Выберите пункт что вы хотите сделать: \n \
  1. Выбрать объект по его id\n \
  2. Обновить объект по его id\n \
  3. Добавить новый обект\n \
  4. Удалить объект по его id\n \
  5. Отфильтровать базу данных по predicate\n \
  6. Exit
